#!/bin/bash
# Variables
echo 'Set mysql root password:\n'
read mysql_root_password
echo 'Enter mysql database name:\n'
read mysql_database_name
echo 'Enter mysql user name:\n'
read mysql_user_name
echo 'Enter mysql user password:\n'
read mysql_user_password
# Update & Upgrade
sudo apt-get update
sudo apt-get upgrade
# Install and setup nginx
sudo apt-get install nginx -y
sudo systemctl start nginx
sudo systemctl enable nginx
#!/bin/bash
# Install and setup php
sudo apt install php7.2 php7.2-curl php7.2-common php7.2-cli php7.2-MySQL php7.2-mbstring php7.2-fpm php7.2-XML php7.2-zip -y
sudo sed -i -e 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/g' /etc/php/7.2/fpm/php.ini
sudo systemctl start php7.2-fpm
sudo systemctl enable php7.2-fpm
# Install and setup mariadb with user and database
sudo apt install mariadb-server mariadb-client -y
sudo mysql -e "UPDATE mysql.user SET Password = PASSWORD('$mysql_root_password') WHERE User = 'root'"
sudo mysql -e "DROP USER ''@'localhost'"
sudo mysql -e "DROP USER ''@'$(hostname)'"
sudo mysql -e "DROP DATABASE test"
sudo mysql -e "FLUSH PRIVILEGES"
sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO '$mysql_user_name'@'localhost' IDENTIFIED BY '$mysql_user_password';"
sudo mysql -e "CREATE DATABASE $mysql_database_name"
# Install composer
sudo apt-get install composer -y
echo '-- Laravel Server Setup Complete --\n\n'
nginx -v
echo '\n\n'
php -v
echo '\n\n'
composer -V
echo '\n\n'
mysql -V